<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyMailandPhone</name>
   <tag></tag>
   <elementGuidId>af809fe6-192c-4986-b6d2-9c45bf85e598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*/p[text()='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*/p[text()='${text}']</value>
   </webElementProperties>
</WebElementEntity>
