<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyNameEdit</name>
   <tag></tag>
   <elementGuidId>083c58d1-0df7-4e7e-bd27-6b4c413c1105</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*/h5[text()='${Name}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*/h5[text()='${Name}']</value>
   </webElementProperties>
</WebElementEntity>
