export const DEVELOPMENT = "DEVELOPMENT";
export const PRODUCTION = "PRODUCTION";
export const INIT_STATE = "INIT_STATE";

//Common
export const NODATA_FAILED = "NODATA_FAILED";
export const API_FAILED = "API_FAILED";

// Login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT ="LOGOUT";

// SignUp
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP ="SIGNUP";

/**
* Manage/customer
**/
export const GET_CUSTOMER_LIST ="GET_CUSTOMER_LIST";
export const GET_CUSTOMER_LIST_REQUEST = "GET_CUSTOMER_LIST_REQUEST";
export const GET_CUSTOMER_LIST_SUCCESS = "GET_CUSTOMER_LIST_SUCCESS";
export const GET_CUSTOMER_LIST_FAILED = "GET_CUSTOMER_LIST_FAILED";

export const GET_CUSTOMER_DETAIL ="GET_CUSTOMER_DETAIL";
export const GET_CUSTOMER_DETAIL_REQUEST = "GET_CUSTOMER_DETAIL_REQUEST";
export const GET_CUSTOMER_DETAIL_SUCCESS = "GET_CUSTOMER_DETAIL_SUCCESS";
export const GET_CUSTOMER_DETAIL_FAILED = "GET_CUSTOMER_DETAIL_FAILED";

export const CUSTOMER_ADD ="CUSTOMER_ADD";
export const CUSTOMER_ADD_REQUEST = "CUSTOMER_ADD_REQUEST";
export const CUSTOMER_ADD_SUCCESS = "CUSTOMER_ADD_SUCCESS";
export const CUSTOMER_ADD_FAILED = "CUSTOMER_ADD_FAILED";

export const GET_PROPERTY_LIST ="GET_PROPERTY_LIST";
export const GET_PROPERTY_LIST_REQUEST = "GET_PROPERTY_LIST_REQUEST";
export const GET_PROPERTY_LIST_SUCCESS = "GET_PROPERTY_LIST_SUCCESS";
export const GET_PROPERTY_LIST_FAILED = "GET_PROPERTY_LIST_FAILED";