<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_DateNew</name>
   <tag></tag>
   <elementGuidId>2caa01c8-bd0f-4847-84ff-511a5a25ab5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[contains(@class,'daySelected')]/../preceding-sibling::div[1]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(@class,'daySelected')]/../preceding-sibling::div[1]/button</value>
   </webElementProperties>
</WebElementEntity>
