<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkBox_influence</name>
   <tag></tag>
   <elementGuidId>defe2d34-556d-40b1-b3c7-0f58e4e64b77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;infl&quot;]//input[@value='${influence}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;infl&quot;]//input[@value='${influence}']</value>
   </webElementProperties>
</WebElementEntity>
