<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyFeatureValuesEdit</name>
   <tag></tag>
   <elementGuidId>35126863-6378-4e42-8771-c62c3c632160</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*/span[contains(text(),'${text}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*/span[contains(text(),'${text}')]</value>
   </webElementProperties>
</WebElementEntity>
