<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_ValuePickerDynamic</name>
   <tag></tag>
   <elementGuidId>8c549951-39cf-4038-a0ab-ada3bc90794c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;${ddid}&quot;]//li[text()='${value}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;${ddid}&quot;]//li[text()='${value}']</value>
   </webElementProperties>
</WebElementEntity>
