<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_VerifySpan</name>
   <tag></tag>
   <elementGuidId>35f9ee14-a856-42d6-85f5-0f6368271525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;realtorPopOverId&quot;]//span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;realtorPopOverId&quot;]//span/input</value>
   </webElementProperties>
</WebElementEntity>
