<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_RealtorValue</name>
   <tag></tag>
   <elementGuidId>48806040-5a33-4c95-9a99-62ee3bf9e2fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;realtorPopOverId&quot;]//input[@value='${realtor}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;realtorPopOverId&quot;]//input[@value='${realtor}']</value>
   </webElementProperties>
</WebElementEntity>
