<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SaveAction</name>
   <tag></tag>
   <elementGuidId>cbf84762-a307-4ee1-b0c9-b6a9a8314018</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button//*[text()='${action}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button//*[text()='${action}']</value>
   </webElementProperties>
</WebElementEntity>
