<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CalendarMeeting</name>
   <tag></tag>
   <elementGuidId>1a7d6dff-ebcd-4090-b413-81e99fa3f0c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;customer_appointmentAdd_startDate&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;customer_appointmentAdd_startDate&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
