<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_dynamicActivity</name>
   <tag></tag>
   <elementGuidId>558617a0-2735-4bc6-b91a-6cb4bd85e050</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;${ddid}&quot;]//li[text()='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;${ddid}&quot;]//li[text()='${text}']</value>
   </webElementProperties>
</WebElementEntity>
