<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_ActivityName</name>
   <tag></tag>
   <elementGuidId>10ba0c1c-abe3-4ea2-8e61-7bb9254629ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h4[contains(text(),'${Meeting}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h4[contains(text(),'${Meeting}')]</value>
   </webElementProperties>
</WebElementEntity>
