<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_SearchMenuTypeDyn</name>
   <tag></tag>
   <elementGuidId>499cdb03-fad5-4373-996b-4530586bb4c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;menu-type&quot;]//ul/li[text()='${type}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;menu-type&quot;]//ul/li[text()='${type}']</value>
   </webElementProperties>
</WebElementEntity>
