<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_Search_RsltText</name>
   <tag></tag>
   <elementGuidId>d30300e7-4bac-452d-9f16-8c6c8c7e0dae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h5</value>
   </webElementProperties>
</WebElementEntity>
