<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_CustomerName</name>
   <tag></tag>
   <elementGuidId>efcf1dc4-3d39-4ea3-aba0-a115171c7be8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[text()='${email}']/../td/span[text()='${customer}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath1</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]//td[text()='${email}']/../td/span[text()='${customer}']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[text()='${email}']/../td/span[text()='${customer}']</value>
   </webElementProperties>
</WebElementEntity>
