<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_CustomerInSearch</name>
   <tag></tag>
   <elementGuidId>a7fc6648-9748-450a-ac50-e5e1257af2e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]//td[text()='${email}']/../td/span[text()='${customer}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]//td[text()='${email}']/../td/span[text()='${customer}']</value>
   </webElementProperties>
</WebElementEntity>
