<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_StageValue</name>
   <tag></tag>
   <elementGuidId>624a0236-8412-4345-a8b1-cf498f4c3aeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;menu-stage&quot;]//li[text()='${Stage}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;menu-stage&quot;]//li[text()='${Stage}']</value>
   </webElementProperties>
</WebElementEntity>
